FROM openjdk:11-jre-slim

# Passed from the terminal
ARG CREDENTIAL_FILE_NAME="credentials.json"
ARG SPRING_ACTIVE_PROFILE="default"
ARG SPRING_DATASOURCE_URL=""
ARG SPRING_DATASOURCE_USERNAME=""
ARG SPRING_DATASOURCE_PASSWORD=""

# Set the environment variables for the image
ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
ENV CREDENTIAL_FILE_NAME=${CREDENTIAL_FILE_NAME}

# Add the .jar file to the image
ADD /build/libs/core-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT ["java","-Dspring.profiles.active=${SPRING_ACTIVE_PROFILE}","-jar","/app.jar"]