services:
  web:
    container_name: retro-board-backend
    environment:
      CREDENTIAL_FILE_NAME: retro-board-credentials.json
      IMAGE_REPOSITORY: registry.gitlab.com/projects2020/retro-board-backend
      IMAGE_TAG: 08fc82595f3ab29a6ddee8c336587257283e2643
      SPRING_ACTIVE_PROFILE: dev
    expose:
    - '8082'
    image: registry.gitlab.com/projects2020/retro-board-backend:08fc82595f3ab29a6ddee8c336587257283e2643
    ports:
    - 8082:8082/tcp
version: '3.0'
volumes:
  mysql_db_data: {}
